### ISSUE TITLE
Add a ValidationAttribute

### ISSUE THREAD

**Issue by feinstein** [jstedfast/EmailValidation#10]
I would like to suggest the addition of a second class to the project, a `ValidationAttribute` (something like [this](https://msdn.microsoft.com/en-us/library/system.componentmodel.dataannotations.emailaddressattribute(v=vs.110).aspx)) so an user can mark an email property with an Attriute and speed up validation. This is specially useful in MVVM scenarios.

**Comment by jstedfast** [comment]
Would you be willing to implement this feature and send me a pull request?

**Comment by feinstein** [comment]
OK, not a problem.

**Comment by feinstein** [comment]
Could you update the Nuget package as well?
