### ISSUE TITLE
Does this work with all current TLD's and check with honeypot

### ISSUE THREAD

**Issue by weedkiller** [jstedfast/EmailValidation#14]
Hi, after searching for a solution I found your awesome nugget!! 🍰 

- [ ] I was wondering if it checked for all TLD's, and how is that updated everyday I see new ones come out.
- [ ] Also can you please [consider honeypot](http://bit.ly/2hvUaY5) as an add-on to this, it would fit naturally.
- [ ] And recaptcha

thanks

**Comment by jstedfast** [comment]
I think you misunderstand what EmailValidation does.

This project only validates the *syntax*, it doesn't validate that the email address exists. That's something that is left for you to do after validating that the syntax is correct.

In other words, EmailValidation can be used to syntax-check text entered into a textbox, but it won't tell you that an email address does somewhere.

**Comment by weedkiller** [comment]
thanks, I was asking for just validating the emails if they meet the current new TLD's - is this doable 

For verification we are sending out SMS - 2 factor auth

**Comment by jstedfast** [comment]
EmailValidation doesn't know anything at all about TLD's and it doesn't need to in order to validate the syntax.
