### ISSUE TITLE
Latest update fails on two of our test cases passed with previous

### ISSUE THREAD

**Issue by Xor-el** [jstedfast/EmailValidation#23]
email@123.123.123.123
abc."defghi".xyz@example.com

is that intended?

**Comment by jstedfast** [comment]
Yes.

In order to use an IPv4 domain, you need to do it like this: `email@[123.123.123.123]`

`abc."defghi".xyz@domain` is also illegal - the local-part be either a dot-atom string -or- a quoted-string, but not a mix of both.

**Comment by Xor-el** [comment]
Thanks for the explanation.
Learnt something new today.
