### ISSUE TITLE
Sign NuGet package

### ISSUE THREAD

**Issue by ghost** [jstedfast/EmailValidation#24]
I would like to use the NuGet package in a project I'm working on, however this project needs to be signed, and as such any references need to be signed as well. Is there any possibility of having the NuGet package signed? I can get the source and sign it myself, but it'd be much more beneficial to keep it pristine and maintain the benefit of simple updates through NuGet.

**Comment by jstedfast** [comment]
Fixed with commit d839f4d5adf5e98e13c73287dfd10c54d701b38d

**Comment by jstedfast** [comment]
Just pushed v1.0.4 that contains signed assemblies.
