### ISSUE TITLE
About temp emails

### ISSUE THREAD

**Issue by sekmenhuseyin** [jstedfast/EmailValidation#26]
Is it possible to disable validation of temp emails like "guerrillamail"

**Comment by jstedfast** [comment]
Not sure what you mean.

**Comment by sekmenhuseyin** [comment]
Disposable Temporary E-Mail Addresses like GuerrillaMail.com, TempMailAddress.com

**Comment by jstedfast** [comment]
All this library does is validate the email address syntax. I.e. it's really only useful in UI's where a user is asked to enter an email address and you want to check that it's valid before allowing them to continue.

This doesn't have any way to disallow certain domains. You'll have to do that yourself.
