### ISSUE TITLE
release fix for max-length bugs

### ISSUE THREAD

**Issue by agentschmitt** [jstedfast/EmailValidation#28]
I am using version 1.0.4 and noticed that domains with fewer then 2 chars are not detected as invalid.
e.g. single-character-tld@ns.i

I found there is already a fix checked in for top-level domains cannot be fewer than 2 characters, but it is not released yet.
https://github.com/jstedfast/EmailValidation/commit/298cd9562a3ba24e00a15e68c9d1d44e6096e590

Could you make a new release with the latest fixes? Would be really cool :)

**Comment by jstedfast** [comment]
Done :)
