### ISSUE TITLE
Some valid domain IP literals fail validation

### ISSUE THREAD

**Issue by JakubJanowski** [jstedfast/EmailValidation#30]
The following are valid email adresses but fail the validation:
`test@[1.1.1.1]`
`test@[IPv6:::]`
`test@[IPv6:::12.34.56.78]`
`test@[IPv6:::3333:4444:5555:6666:7777:8888]`

I suspect that the first two fail because of this check:
```C#
// we need at least 8 more characters
if (index + 8 >= email.Length)
    return false;
```
but I'm not sure about the last two. This one for example passes validation correctly:
`test@[IPv6:::b3:b4]`

**Comment by jstedfast** [comment]
This is the relevant spec: https://datatracker.ietf.org/doc/html/rfc2821#section-4.1.3

`test@[1.1.1.1]` should definitely pass and the check should be `+ 7` instead of `+ 8` as you said.

Given the following syntax, I don't see how your other examples should pass:

```
IPv6-addr = IPv6-full / IPv6-comp / IPv6v4-full / IPv6v4-comp
IPv6-hex  = 1*4HEXDIG
IPv6-full = IPv6-hex 7(":" IPv6-hex)
IPv6-comp = [IPv6-hex *5(":" IPv6-hex)] "::" [IPv6-hex *5(":" IPv6-hex)]
            ; The "::" represents at least 2 16-bit groups of zeros
            ; No more than 6 groups in addition to the "::" may be
            ; present
IPv6v4-full = IPv6-hex 5(":" IPv6-hex) ":" IPv4-address-literal
IPv6v4-comp = [IPv6-hex *3(":" IPv6-hex)] "::"
            [IPv6-hex *3(":" IPv6-hex) ":"] IPv4-address-literal
            ; The "::" represents at least 2 16-bit groups of zeros
            ; No more than 4 groups in addition to the "::" and
            ; IPv4-address-literal may be present
```

**Comment by JakubJanowski** [comment]
Thanks for looking into this.

[RFC 2821](https://datatracker.ietf.org/doc/html/rfc2821#section-4.1.3) was obsoleted by [RFC 5321](https://datatracker.ietf.org/doc/html/rfc5321#section-4.1.3) but it seems you quoted the correct syntax.

As I understand it, stuff enclosed in square brackets `[]` is optional therefore the first part of IPv6-comp definition 
`[IPv6-hex *5(":" IPv6-hex)]` means it can optionally consist of one `IPv6-hex` followed by 0 to 5 instances of `(":" IPv6-hex)`

`test@[IPv6:::]` matches `IPv6-comp` definition in that it does not have any of the optional parts enclosed in square brackets and contains the required part of `"::"`

`test@[IPv6:::12.34.56.78]` matches `IPv6v4-comp` - omits optional part of `[IPv6-hex *3(":" IPv6-hex)]`, then `"::"`, then omits optional part `[IPv6-hex *3(":" IPv6-hex) ":"]`, then `IPv4-address-literal`

`test@[IPv6:::3333:4444:5555:6666:7777:8888]` matches `IPv6-comp` - omits optional part of `[IPv6-hex *5(":" IPv6-hex)]`, then `"::"`, then the rest (`3333:4444:5555:6666:7777:8888`) matches `[IPv6-hex *5(":" IPv6-hex)]` - one instance of `IPv6-hex` (`3333`) followed by 5 of `(":" IPv6-hex)` (`:4444:5555:6666:7777:8888`)
