### ISSUE TITLE
Problematic emails

### ISSUE THREAD

**Issue by bkanak** [jstedfast/EmailValidation#36]
Hi, are emails: 

günter@blitzkrieg.com
majka.jeżowska@bar.pl
あいうえお@example.com

correct?
![image](https://user-images.githubusercontent.com/82027170/173017621-9c49438f-17ce-4d20-b740-d4cc2be9fa25.png)

**Comment by jstedfast** [comment]
What parameters are you passing to the IsValid method?

**Comment by jstedfast** [comment]
And yes, they are correct

**Comment by bkanak** [comment]
OK, I those email addresses conform standards but they don't conform synctatic rules of target mail exchangers.
Thanks
