### ISSUE TITLE
Is it possible to find out the reason why the mail is invalid?

### ISSUE THREAD

**Issue by reponemec** [jstedfast/EmailValidation#42]
Is it possible to find out the reason why the mail is invalid? Some friendly message...
Thanks.

**Comment by jstedfast** [comment]
I suppose so. How detailed do you need it to be?

**Comment by reponemec** [comment]
Supposing "invalid" address "john gray@domain.com". Then the validation error could be:
```json
{
    "Code": "InvalidCharacter",
    "Description": "Invalid character {0} at {1}.",
    "Params": [" ", 4]
}
```
Translatable. Inspired a bit by IdentityError: https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.identityerror?view=aspnetcore-7.0

**Comment by jstedfast** [comment]
Added
