### ISSUE TITLE
allowInternational breaks with four-byte UTF-8 characters

### ISSUE THREAD

**Issue by JakubJanowski** [jstedfast/EmailValidation#44]
Hi,

Due to the limitations of .NET's implementation of `string` with UTF-16, characters from the upper end like `"\U00010348"` (`𐍈`) have a length of 2. This unfortunately breaks length checks in the validator.

For example:
`"test@𐍈"` passes the validation, while other single-character TLD addresses don't
`"𐍈𐍈𐍈𐍈𐍈𐍈𐍈𐍈𐍈𐍈𐍈𐍈𐍈𐍈𐍈𐍈𐍈𐍈𐍈𐍈𐍈𐍈𐍈𐍈𐍈𐍈𐍈𐍈𐍈𐍈𐍈𐍈𐍈@example.com"` doesn't pass 64-character local part length check, even though it has 33 characters.

I don't think there is a built-in function to get character count in a string, but maybe [`char.IsSurrogatePair()`](https://learn.microsoft.com/en-us/dotnet/api/system.char.issurrogatepair?view=net-6.0) will be of use.

**Comment by jstedfast** [comment]
Thanks for the bug report.

Yes, char.IsSurrogatePair() is the way to solve this. I use this approach when encoding headers in MimeKit.
