### ISSUE TITLE
Any chance of a NuGet package?

### ISSUE THREAD

**Issue by natiki** [jstedfast/EmailValidation#7]
Hi,

As a user of MimeKit I was happy to come across this simple class. I was wondering if you would consider publishing a NuGet package?

Or at worst is there a way to access the same functionalty within MimeKit?

**Comment by jstedfast** [comment]
I'll look into publishing a nuget soon. I might not have time this week, though.

MimeKit's email address parser actually follows a slightly different set of rules in that the MIME specs differ from the SMTP specs (MIME allows all sorts of whitespace and comments embedded in the email address tokens while SMTP does not).

EmailValidation follows the SMTP spec and is thus a bit more strict.

**Comment by natiki** [comment]
Thanks. I have grabbed the code so I am all good for now. NuGet can come when you have the time.

**Comment by BlueFire-LLC** [comment]
I'd like the NuGet package. It makes it more consistent with the other packages in my app including MimeKit. Or better yet why not just add it as a method to MimeKit (eg. InternetAddress.SmtpParse(EmailAddress)).

**Comment by jstedfast** [comment]
Sorry, kept forgetting to make a nuget. It's published now.

**Comment by natiki** [comment]
@jstedfast Legend. Much appreciated.
